"use client";

import { useLang } from "@/lib/lang";
import {
  Prose, Wide, B, C, SH, P, Callout,
  MetricStrip, NextProject, ArticleHeader, BackLink,
} from "../_article";

const en = {
  subtitle:
    "A Gaussian Mixture Model on 11 audio features + 48-dim genre embeddings that discovers the latent 'vibes' in a Spotify library and rebuilds them as playlists — named by a local LLM.",
  openP1:
    "After years of saving songs to Spotify, my library became a single undifferentiated bucket of a few thousand tracks. Great for shuffle on a long trip. Completely useless for finding the right music for a specific moment — late-night coding, Sunday morning coffee, a run.",
  openP2:
    "The standard solution is manual curation. I'd started seven different \"vibes\" playlists, abandoned six of them, and never caught up with newly saved tracks. The problem wasn't motivation — it was friction. Manually sorting 2,000+ songs is a task no one actually does.",
  openP3:
    "The question: could an unsupervised model discover the actual vibes hiding in my listening history and reconstruct them as playlists automatically — without me having to label anything?",

  pipelineStages: [
    { icon: "🎵", label: "Spotify OAuth", sub: "full library pull via Spotipy", color: "#3b82f6" },
    { icon: "📊", label: "Audio Features", sub: "11 features · ReccoBeats API", color: "#8b5cf6" },
    { icon: "⚙️", label: "Feature Engineering", sub: "key → circular · genre TF-IDF + SVD", color: "#f97316" },
    { icon: "🔵", label: "GMM Clustering", sub: "auto-K · silhouette + BIC", color: "#ec4899" },
    { icon: "🤖", label: "LLM Naming", sub: "Llama 3 via Ollama · centroid → name", color: "#22d3ee" },
    { icon: "✅", label: "Spotify Write-back", sub: "one playlist per cluster · parallel", color: "#a3e635" },
  ] as { icon: string; label: string; sub: string; color: string }[],
  fig1label: "Fig 1.",
  fig1caption: "End-to-end pipeline from Spotify OAuth to playlist write-back. The entire flow is reproducible from a single script with a DEV_MODE flag that previews clusters before touching Spotify.",

  kSelectedLabel: "selected K=7",
  kBicLabel: "BIC ↓ (better)",
  kSilLabel: "Silhouette ↑",
  kXLabel: "Number of Clusters K",
  fig2label: "Fig 2.",
  fig2caption: "K selection via silhouette score (maximize, green) and BIC (minimize, blue). K=7 is the agreement point — both metrics peak here for an 800-song library. The search range scales with library size: K ∈ [n/200, n/80].",

  clusterCardHeader: "Sample clusters generated by Llama 3 naming — 800-song library",
  clusterCards: [
    { name: "Late-Night Focus Electronic", features: "instrumentalness 0.91 · energy 0.62 · valence 0.24 · tempo 128bpm", tracks: ["Jon Hopkins — Emerald Rush", "Bicep — Glue", "Four Tet — Angel Echoes"], color: "#8b5cf6" },
    { name: "High-Energy Running Mix", features: "danceability 0.88 · energy 0.94 · valence 0.71 · tempo 148bpm", tracks: ["Drake — Started From the Bottom", "Travis Scott — SICKO MODE", "Kanye — All Falls Down"], color: "#f97316" },
    { name: "Sunday Morning Acoustic", features: "acousticness 0.87 · energy 0.28 · valence 0.58 · speechiness 0.04", tracks: ["Rex Orange County — Loving Is Easy", "Mac DeMarco — Chamber of Reflection", "Sufjan Stevens — Death With Dignity"], color: "#a3e635" },
  ] as { name: string; features: string; tracks: string[]; color: string }[],
  fig3label: "Fig 3.",
  fig3caption: "Three of the seven auto-generated clusters with their Llama 3 names, dominant audio feature signatures, and sample tracks. Cluster names were used as-is — no manual editing.",

  s1step: "Step 01",
  s1title: "Data: 11 Audio Features + Genre Embeddings",
  s1p1pre: "Spotify's audio features API provides 11 per-track signals: ",
  s1p1bold: "danceability, energy, valence, tempo, acousticness, liveness, loudness, speechiness, instrumentalness, key, mode",
  s1p1post: ". These capture a song's sonic character — how danceable it is, how much acoustic sound vs electronic production, how emotionally positive or negative it feels.",
  s1p2pre: "Audio features alone turned out to be insufficient. Genres carry information that raw audio features don't — the difference between ambient jazz and ambient electronic might be small in feature space but large in listener experience. To capture this, I built a ",
  s1p2b1: "TF-IDF representation of genre tags",
  s1p2mid: " (vocabulary capped at 600 terms) and compressed it to ",
  s1p2b2: "48 latent dimensions",
  s1p2post: " using Truncated SVD. The numeric and genre features are then fused into a single feature vector per track.",
  callout: "Genre embeddings dominated the latent space. Audio features alone confused jazz with ambient — both have low energy, high acousticness, low valence. The genre embedding separated them immediately. The lesson: sometimes the most useful signal is a human-generated label, not a continuous measurement.",

  s2step: "Step 02",
  s2title: "Feature Engineering: Circular Key Encoding",
  s2p: "One non-obvious preprocessing step: musical key is circular. Key C (0) is adjacent to key B (11) — they're a half-step apart in music theory. Treating key as an ordinal variable (0–11) tells the model that C and B are maximally dissimilar. The fix: encode key as (sin(2π·key/12), cos(2π·key/12)), which preserves the circular relationship. This meaningfully improved cluster cohesion.",

  s3step: "Step 03",
  s3title: "Clustering: GMM with Auto-K Selection",
  s3p1pre: "I chose a ",
  s3p1bold: "Gaussian Mixture Model",
  s3p1post: " over k-means for two reasons: (1) GMM assigns soft cluster membership probabilities rather than hard assignments, which is more honest about songs that sit at the boundary between vibes, and (2) GMM better handles the ellipsoidal cluster shapes that arise from correlated feature dimensions in music.",
  s3p2: "The number of clusters K is not hard-coded. It's auto-selected from a data-scaled range: K ∈ [n/200, n/80], where n is the library size. This means the tool is useful for both 200-song and 5,000-song libraries without any manual configuration. Within that range, the selected K maximizes silhouette score, with BIC as a tie-breaker.",

  s4step: "Step 04",
  s4title: "Naming Clusters with a Local LLM",
  s4p1pre: "Each cluster's centroid (the average audio feature vector) plus a random sample of 10 tracks and their genres is passed as context to ",
  s4p1bold: "Llama 3 running locally via Ollama",
  s4p1post: ". The prompt asks for a playlist name that captures the vibe — 2–4 words, evocative, not generic.",
  s4p2: "The LLM-generated names worked well enough that I shipped them as-is on the first library run — no manual editing. The model naturally landed on names like \"Late-Night Focus Electronic,\" \"Sunday Morning Acoustic,\" and \"High-Energy Running Mix.\" These are exactly the kind of names I'd have given the playlists myself.",

  metrics: [
    { label: "audio features modeled per track", value: "11", sub: "Spotify + ReccoBeats API" },
    { label: "genre embedding dimensions", value: "48", sub: "TF-IDF (600 vocab) + SVD" },
    { label: "auto-K range", value: "n/200–n/80", sub: "scales with library size" },
    { label: "write-back workers", value: "16", sub: "ThreadPoolExecutor · parallel" },
  ] as { label: string; value: string; sub: string }[],

  s5step: "What This Gets Right",
  s5title: "Three Things That Mattered",
  s5p1bold: "1. Circular encoding of musical key is a small fix with outsized impact.",
  s5p1: " Treating key as ordinal was technically wrong — C and B are adjacent, not maximally distant. The circular encoding preserved that relationship and improved cluster cohesion measurably.",
  s5p2bold: "2. Genre embeddings are the most important feature family.",
  s5p2: " Raw audio features alone grouped by sonic texture (loud vs quiet, fast vs slow) in ways that didn't match musical intuition. Adding genre embeddings aligned the clusters with how humans actually categorize music — by style, not just by signal properties.",
  s5p3bold: "3. Letting K scale with library size made the tool actually reusable.",
  s5p3: " Hard-coding K=8 would have produced reasonable clusters for my 800-song library and terrible ones for a friend's 5,000-song archive. Data-scaled auto-K means I can run the same script on any library.",
};

const es: typeof en = {
  subtitle:
    "Un Modelo de Mezcla Gaussiana sobre 11 características de audio + embeddings de género de 48 dimensiones que descubre las 'vibras' latentes en una biblioteca de Spotify y las reconstruye como playlists — nombradas por un LLM local.",
  openP1:
    "Tras años de guardar canciones en Spotify, mi biblioteca se convirtió en un único cubo indiferenciado de algunos miles de pistas. Genial para aleatorio en un viaje largo. Completamente inútil para encontrar la música correcta para un momento específico — programación nocturna, café del domingo por la mañana, un paseo.",
  openP2:
    "La solución estándar es la curación manual. Había empezado siete playlists de 'vibras' diferentes, abandoné seis, y nunca me puse al día con las nuevas pistas guardadas. El problema no era la motivación — era la fricción. Ordenar manualmente más de 2.000 canciones es una tarea que nadie hace realmente.",
  openP3:
    "La pregunta: ¿podría un modelo no supervisado descubrir las vibras reales que se esconden en mi historial de escucha y reconstruirlas como playlists automáticamente — sin que yo tenga que etiquetar nada?",

  pipelineStages: [
    { icon: "🎵", label: "Spotify OAuth", sub: "obtención completa de la biblioteca vía Spotipy", color: "#3b82f6" },
    { icon: "📊", label: "Características de Audio", sub: "11 características · API ReccoBeats", color: "#8b5cf6" },
    { icon: "⚙️", label: "Ingeniería de Características", sub: "tonalidad → circular · género TF-IDF + SVD", color: "#f97316" },
    { icon: "🔵", label: "Clustering GMM", sub: "K automático · silhouette + BIC", color: "#ec4899" },
    { icon: "🤖", label: "Nombrado por LLM", sub: "Llama 3 vía Ollama · centroide → nombre", color: "#22d3ee" },
    { icon: "✅", label: "Escritura en Spotify", sub: "una playlist por clúster · paralelo", color: "#a3e635" },
  ],
  fig1label: "Fig 1.",
  fig1caption: "Pipeline de extremo a extremo desde Spotify OAuth hasta la escritura de playlists. Todo el flujo es reproducible desde un único script con un flag DEV_MODE que previsualiza los clústeres antes de tocar Spotify.",

  kSelectedLabel: "K=7 seleccionado",
  kBicLabel: "BIC ↓ (mejor)",
  kSilLabel: "Silhouette ↑",
  kXLabel: "Número de Clústeres K",
  fig2label: "Fig 2.",
  fig2caption: "Selección de K mediante puntuación de silhouette (maximizar, verde) y BIC (minimizar, azul). K=7 es el punto de acuerdo — ambas métricas alcanzan su pico aquí para una biblioteca de 800 canciones. El rango de búsqueda escala con el tamaño de la biblioteca: K ∈ [n/200, n/80].",

  clusterCardHeader: "Clústeres de muestra generados por el nombrado de Llama 3 — biblioteca de 800 canciones",
  clusterCards: [
    { name: "Late-Night Focus Electronic", features: "instrumentalidad 0.91 · energía 0.62 · valencia 0.24 · tempo 128bpm", tracks: ["Jon Hopkins — Emerald Rush", "Bicep — Glue", "Four Tet — Angel Echoes"], color: "#8b5cf6" },
    { name: "High-Energy Running Mix", features: "bailabilidad 0.88 · energía 0.94 · valencia 0.71 · tempo 148bpm", tracks: ["Drake — Started From the Bottom", "Travis Scott — SICKO MODE", "Kanye — All Falls Down"], color: "#f97316" },
    { name: "Sunday Morning Acoustic", features: "acústica 0.87 · energía 0.28 · valencia 0.58 · discurso 0.04", tracks: ["Rex Orange County — Loving Is Easy", "Mac DeMarco — Chamber of Reflection", "Sufjan Stevens — Death With Dignity"], color: "#a3e635" },
  ],
  fig3label: "Fig 3.",
  fig3caption: "Tres de los siete clústeres auto-generados con sus nombres de Llama 3, firmas de características de audio dominantes y pistas de muestra. Los nombres de clúster se usaron tal cual — sin edición manual.",

  s1step: "Paso 01",
  s1title: "Datos: 11 Características de Audio + Embeddings de Género",
  s1p1pre: "La API de características de audio de Spotify proporciona 11 señales por pista: ",
  s1p1bold: "bailabilidad, energía, valencia, tempo, acústica, presencia de público, sonoridad, discurso, instrumentalidad, tonalidad y modo",
  s1p1post: ". Estas capturan el carácter sonoro de una canción — qué tan bailable es, cuánto sonido acústico vs producción electrónica tiene, qué tan positiva o negativa se siente emocionalmente.",
  s1p2pre: "Solo las características de audio resultaron insuficientes. Los géneros llevan información que las características de audio en bruto no capturan — la diferencia entre jazz ambiental y electrónica ambiental puede ser pequeña en el espacio de características pero grande en la experiencia del oyente. Para capturar esto, construí una ",
  s1p2b1: "representación TF-IDF de etiquetas de género",
  s1p2mid: " (vocabulario limitado a 600 términos) y la comprimí a ",
  s1p2b2: "48 dimensiones latentes",
  s1p2post: " usando SVD Truncado. Las características numéricas y de género se fusionan luego en un único vector de características por pista.",
  callout: "Los embeddings de género dominaron el espacio latente. Las características de audio solas confundían jazz con ambiental — ambos tienen baja energía, alta acústica, baja valencia. El embedding de género los separó inmediatamente. La lección: a veces la señal más útil es una etiqueta generada por humanos, no una medición continua.",

  s2step: "Paso 02",
  s2title: "Ingeniería de Características: Codificación Circular de la Tonalidad",
  s2p: "Un paso de preprocesamiento no obvio: la tonalidad musical es circular. La tonalidad Do (0) es adyacente a la tonalidad Si (11) — están a un semitono de distancia en teoría musical. Tratar la tonalidad como una variable ordinal (0–11) le dice al modelo que Do y Si son maximalmente disimilares. La solución: codificar la tonalidad como (sin(2π·tonalidad/12), cos(2π·tonalidad/12)), lo que preserva la relación circular. Esto mejoró notablemente la cohesión del clúster.",

  s3step: "Paso 03",
  s3title: "Clustering: GMM con Selección Automática de K",
  s3p1pre: "Elegí un ",
  s3p1bold: "Modelo de Mezcla Gaussiana",
  s3p1post: " en lugar de k-means por dos razones: (1) el GMM asigna probabilidades de pertenencia suave al clúster en lugar de asignaciones duras, lo que es más honesto sobre las canciones que se encuentran en el límite entre vibras, y (2) el GMM maneja mejor las formas de clúster elipsoidales que surgen de dimensiones de características correlacionadas en música.",
  s3p2: "El número de clústeres K no está codificado. Se auto-selecciona desde un rango escalado por datos: K ∈ [n/200, n/80], donde n es el tamaño de la biblioteca. Esto significa que la herramienta es útil tanto para bibliotecas de 200 canciones como de 5.000 sin ninguna configuración manual. Dentro de ese rango, el K seleccionado maximiza la puntuación de silhouette, con BIC como desempate.",

  s4step: "Paso 04",
  s4title: "Nombrar Clústeres con un LLM Local",
  s4p1pre: "El centroide de cada clúster (el vector promedio de características de audio) más una muestra aleatoria de 10 pistas y sus géneros se pasa como contexto a ",
  s4p1bold: "Llama 3 ejecutándose localmente vía Ollama",
  s4p1post: ". El prompt pide un nombre de playlist que capture la vibra — 2–4 palabras, evocador, no genérico.",
  s4p2: "Los nombres generados por LLM funcionaron lo suficientemente bien como para enviarlos tal cual en la primera ejecución de la biblioteca — sin edición manual. El modelo aterrizó naturalmente en nombres como «Late-Night Focus Electronic», «Sunday Morning Acoustic» y «High-Energy Running Mix». Son exactamente los nombres que yo mismo habría dado a las playlists.",

  metrics: [
    { label: "características de audio modeladas por pista", value: "11", sub: "API de Spotify + ReccoBeats" },
    { label: "dimensiones de embedding de género", value: "48", sub: "TF-IDF (vocab. 600) + SVD" },
    { label: "rango auto-K", value: "n/200–n/80", sub: "escala con el tamaño de la biblioteca" },
    { label: "workers de escritura", value: "16", sub: "ThreadPoolExecutor · paralelo" },
  ],

  s5step: "Lo Que Funciona",
  s5title: "Tres Cosas que Importaron",
  s5p1bold: "1. La codificación circular de la tonalidad musical es una pequeña corrección con gran impacto.",
  s5p1: " Tratar la tonalidad como ordinal era técnicamente incorrecto — Do y Si son adyacentes, no maximalmente distantes. La codificación circular preservó esa relación y mejoró la cohesión del clúster de manera medible.",
  s5p2bold: "2. Los embeddings de género son la familia de características más importante.",
  s5p2: " Las características de audio solas agrupaban por textura sónica (fuerte vs silencioso, rápido vs lento) de maneras que no coincidían con la intuición musical. Añadir embeddings de género alineó los clústeres con cómo los humanos categorizan realmente la música — por estilo, no solo por propiedades de señal.",
  s5p3bold: "3. Dejar que K escale con el tamaño de la biblioteca hizo que la herramienta fuera realmente reutilizable.",
  s5p3: " Codificar K=8 habría producido clústeres razonables para mi biblioteca de 800 canciones y pésimos para el archivo de 5.000 canciones de un amigo. El K auto escalado por datos significa que puedo ejecutar el mismo script en cualquier biblioteca.",
};

// ── Diagram components ────────────────────────────────────────────────────────

function PipelineFlow({ tx }: { tx: typeof en }) {
  return (
    <figure className="select-none">
      <div className="rounded-xl bg-bg-elev/50 border border-border p-6">
        <div className="flex flex-col sm:flex-row items-stretch gap-0">
          {tx.pipelineStages.map((s, i) => (
            <div key={s.label} className="flex sm:flex-col items-center flex-1 min-w-0">
              <div className="rounded-xl border px-2.5 py-3 text-center flex-1 w-full" style={{ borderColor: s.color + "55", background: s.color + "10" }}>
                <p className="text-lg mb-0.5">{s.icon}</p>
                <p className="text-xs font-semibold text-ink leading-snug">{s.label}</p>
                <p className="text-[10px] text-ink-muted mt-0.5 leading-snug hidden sm:block">{s.sub}</p>
              </div>
              {i < tx.pipelineStages.length - 1 && (
                <>
                  <div className="flex sm:hidden w-5 shrink-0 items-center justify-center text-ink-subtle">→</div>
                  <div className="hidden sm:flex h-4 w-full items-center justify-center text-ink-subtle text-sm">→</div>
                </>
              )}
            </div>
          ))}
        </div>
      </div>
      <figcaption className="mt-3 text-xs text-ink-subtle text-center">
        <span className="text-ink-muted font-medium">{tx.fig1label}</span>{" "}{tx.fig1caption}
      </figcaption>
    </figure>
  );
}

function KSelectionChart({ tx }: { tx: typeof en }) {
  const W = 520, H = 210;
  const pl = 44, pr = 20, pt = 20, pb = 42;
  const cW = W - pl - pr, cH = H - pt - pb;
  const ks = [4, 5, 6, 7, 8, 9, 10];
  const silhouette = [0.31, 0.38, 0.44, 0.47, 0.43, 0.39, 0.35];
  const bic = [4820, 4640, 4510, 4480, 4530, 4620, 4750];
  const xk = (i: number) => pl + (i / (ks.length - 1)) * cW;
  const ySil = (v: number) => pt + cH - ((v - 0.28) / 0.22) * cH;
  const yBic = (v: number) => pt + cH - ((4800 - v) / 380) * cH;
  const silPath = silhouette.map((v, i) => `${i === 0 ? "M" : "L"}${xk(i).toFixed(1)},${ySil(v).toFixed(1)}`).join(" ");
  const bicPath = bic.map((v, i) => `${i === 0 ? "M" : "L"}${xk(i).toFixed(1)},${yBic(v).toFixed(1)}`).join(" ");

  return (
    <figure className="select-none">
      <div className="rounded-xl bg-bg-elev/50 border border-border p-5 pb-3">
        <svg viewBox={`0 0 ${W} ${H}`} className="w-full" aria-hidden="true">
          <line x1={pl} y1={pt} x2={pl} y2={pt + cH} stroke="rgba(255,255,255,0.1)" />
          <line x1={pl} y1={pt + cH} x2={pl + cW} y2={pt + cH} stroke="rgba(255,255,255,0.1)" />
          {ks.map((k, i) => (
            <g key={k}>
              <line x1={xk(i)} y1={pt} x2={xk(i)} y2={pt + cH} stroke="rgba(255,255,255,0.05)" />
              <text x={xk(i)} y={pt + cH + 14} textAnchor="middle" fill="rgba(255,255,255,0.35)" fontSize={9}>K={k}</text>
            </g>
          ))}
          <path d={bicPath} fill="none" stroke="#3b82f6" strokeWidth={2} strokeLinejoin="round" strokeDasharray="5,2" />
          {bic.map((v, i) => <circle key={i} cx={xk(i)} cy={yBic(v)} r={3} fill="#3b82f6" />)}
          <path d={silPath} fill="none" stroke="#a3e635" strokeWidth={2.5} strokeLinejoin="round" />
          {silhouette.map((v, i) => <circle key={i} cx={xk(i)} cy={ySil(v)} r={3.5} fill="#a3e635" />)}
          <line x1={xk(3)} y1={pt} x2={xk(3)} y2={pt + cH} stroke="#a3e635" strokeOpacity={0.4} strokeDasharray="3,2" />
          <text x={xk(3) + 3} y={pt + 10} fill="#a3e635" fontSize={9}>{tx.kSelectedLabel}</text>
          <line x1={pl + 6} y1={pt + 20} x2={pl + 20} y2={pt + 20} stroke="#a3e635" strokeWidth={2.5} />
          <text x={pl + 24} y={pt + 24} fill="rgba(255,255,255,0.6)" fontSize={9}>{tx.kSilLabel}</text>
          <line x1={pl + 110} y1={pt + 20} x2={pl + 124} y2={pt + 20} stroke="#3b82f6" strokeWidth={2} strokeDasharray="5,2" />
          <text x={pl + 128} y={pt + 24} fill="rgba(255,255,255,0.6)" fontSize={9}>{tx.kBicLabel}</text>
          <text x={pl + cW / 2} y={H - 5} textAnchor="middle" fill="rgba(255,255,255,0.3)" fontSize={9}>{tx.kXLabel}</text>
        </svg>
      </div>
      <figcaption className="mt-3 text-xs text-ink-subtle text-center">
        <span className="text-ink-muted font-medium">{tx.fig2label}</span>{" "}{tx.fig2caption}
      </figcaption>
    </figure>
  );
}

function ClusterCards({ tx }: { tx: typeof en }) {
  return (
    <figure className="select-none">
      <div className="rounded-xl bg-bg-elev/50 border border-border p-6">
        <p className="font-mono text-[10px] uppercase tracking-widest text-ink-subtle mb-4">{tx.clusterCardHeader}</p>
        <div className="grid sm:grid-cols-3 gap-3">
          {tx.clusterCards.map(({ name, features, tracks, color }) => (
            <div key={name} className="rounded-xl border p-4" style={{ borderColor: color + "40", background: color + "08" }}>
              <p className="text-sm font-semibold text-ink mb-2 leading-snug">{name}</p>
              <p className="text-[10px] font-mono text-ink-subtle mb-3 leading-relaxed">{features}</p>
              <div className="space-y-1">
                {tracks.map((t) => <p key={t} className="text-[11px] text-ink-muted leading-snug">• {t}</p>)}
              </div>
            </div>
          ))}
        </div>
      </div>
      <figcaption className="mt-3 text-xs text-ink-subtle text-center">
        <span className="text-ink-muted font-medium">{tx.fig3label}</span>{" "}{tx.fig3caption}
      </figcaption>
    </figure>
  );
}

// ── Page ──────────────────────────────────────────────────────────────────────

export default function MusicRecommenderContent() {
  const { lang } = useLang();
  const tx = lang === "es" ? es : en;

  return (
    <article className="pt-32 pb-24">
      <BackLink />
      <ArticleHeader
        eyebrow="Personal Project · 2025"
        title="MusicAI — Playlist Auto-Clusterer"
        subtitle={tx.subtitle}
        tags={["Unsupervised Learning", "Gaussian Mixture Model", "Spotify API", "TF-IDF + SVD", "Ollama", "Llama 3"]}
      />

      <div className="container-page mt-16">
        <Prose>
          <P>{tx.openP1}</P>
          <P>{tx.openP2}</P>
          <P>{tx.openP3}</P>
        </Prose>

        <Prose>
          <SH id="data" step={tx.s1step}>{tx.s1title}</SH>
          <P>{tx.s1p1pre}<B>{tx.s1p1bold}</B>{tx.s1p1post}</P>
          <P>{tx.s1p2pre}<B>{tx.s1p2b1}</B>{tx.s1p2mid}<B>{tx.s1p2b2}</B>{tx.s1p2post}</P>
          <Callout>{tx.callout}</Callout>
        </Prose>

        <Prose>
          <SH id="clustering" step={tx.s2step}>{tx.s2title}</SH>
          <P>{tx.s2p}</P>
        </Prose>

        <Wide><PipelineFlow tx={tx} /></Wide>

        <Prose>
          <SH id="gmm" step={tx.s3step}>{tx.s3title}</SH>
          <P>{tx.s3p1pre}<B>{tx.s3p1bold}</B>{tx.s3p1post}</P>
          <P>{tx.s3p2}</P>
        </Prose>

        <Wide><KSelectionChart tx={tx} /></Wide>

        <Prose>
          <SH id="naming" step={tx.s4step}>{tx.s4title}</SH>
          <P>{tx.s4p1pre}<B>{tx.s4p1bold}</B>{tx.s4p1post}</P>
          <P>{tx.s4p2}</P>
        </Prose>

        <Wide><ClusterCards tx={tx} /></Wide>

        <MetricStrip metrics={tx.metrics} />

        <Prose>
          <SH id="takeaways" step={tx.s5step}>{tx.s5title}</SH>
          <P><B>{tx.s5p1bold}</B>{tx.s5p1}</P>
          <P><B>{tx.s5p2bold}</B>{tx.s5p2}</P>
          <P><B>{tx.s5p3bold}</B>{tx.s5p3}</P>
        </Prose>

        <NextProject slug="enertex-cto" />
      </div>
    </article>
  );
}
